### ISSUE TITLE
Spam and Security - Review and Implement

### ISSUE THREAD

**Issue by bibliography** [bibliowiki/bibliowiki#10]

**Comment by jeffmcneill** [comment]
Antispam/Antivandal Measures and Best Practices - Ensure the previous spam problem doesn't reoccur - 

open account creation currently, need to research the antispam measures:


http://stackoverflow.com/questions/6748633/prevent-mediawiki-from-being-spammed
https://www.mediawiki.org/wiki/Extension:AntiBot
https://www.mediawiki.org/wiki/Manual:Combating_spam
https://www.mediawiki.org/wiki/Manual:Combating_vandalism
https://www.mediawiki.org/wiki/Talk:Anti-spam_features

**Comment by jeffmcneill** [comment]
Take a close look at what is already documented:

https://github.com/bibliowiki/bibliowiki/blob/master/security-and-antispam.md

**Comment by jeffmcneill** [comment]
Everything is basically fixed by making new account requests be through email. Spam has been conquered by requiring a human request an account, and a human approve an account request.
